### ISSUE TITLE
When I mistype my password, the warning message is scarier than necessary

### ISSUE THREAD

**Issue by maxjacobson** [conradkleinespel/rooster#12]
Hello again!

Currently when I `rooster get github`, for example, and mistype my master password, the output looks like this:

```
I could not upgrade the Rooster file. This could be because:
- you explicitly told Rooster not to open the file,
- your version of Rooster is outdated,
- your Rooster file is corrupted,
- your master password is wrong.
Try upgrading to the latest version of Rooster.
```

IMO rooster should know which scenario has occurred, and print just the most accurate thing.

**Comment by conradkleinespel** [comment]
Hello @maxjacobson,

Thanks for telling us about that ! :+1:

You are totally right, the message is scary for newcomers, and I'm sorry about that. Luckily, there are some things we could do.

We could, for instance, have 3 different messages:
- one in the case the Rooster file has permissions that don't allow Rooster to open it (the 1st line in your example),
- one in the case the version of Rooster is outdated (the 2nd line in your example)
- one in the case the Rooster file is corrupted or the password is wrong (the 3rd and 4th lines)

However, if the file is corrupted on the part that stores the Rooster file version, than we might say:
> You need to upgrade Rooster.

Instead of saying:
> Your file is corrupted.

That is unlikely though. But maybe we could say something like:
> If your problem persists, open an issue here: https://github.com/conradkleinespel/rooster/issues

@maxjacobson what do you think, would that be better ? what would you suggest we do ?

— Conrad

**Comment by maxjacobson** [comment]
Thanks for the thoughtful response! IMO the more specific rooster can be, the better.

I'm glad to hear that it sounds like it is possible to improve this. I realized after opening this issue that (having not really looked at the code around this) it might not be clear the reason that the provided master password didn't successfully authorize reading from the file.

It does sound like that is _kind of_ the case, but there are still improvements to make. I would focus on improving the output in this scenario:

> one in the case the Rooster file is corrupted or the password is wrong (the 3rd and 4th lines)

And to print something like

> I could not decrypt the Rooster file with that password. Please try again.

Mentioning the issue tracker is generous. Mentioning the possibility of a corrupt file is kind of scary. You can mention both if you want, but I'm not sure if they're necessary, personally.

Ideally it would be possible for Rooster tell whether the password is wrong _or_ the Rooster file is corrupted, but if there's no good way to tell, so be it.

**Comment by conradkleinespel** [comment]
The message you suggest we use for the scenario where the password is wrong sounds good to me :+1: 

If you **have the time** to work on this, I'd be glad to help you if needed. And I'd be **glad to merge a pull request** :smiley:

If you **don't have the time** to work on this, **it's fine too, of course**. I'll get to doing this eventually, but I don't have an ETA.

--

In case you're interested in knowing why we can't know whether the password is wrong or the file is corrupted, here's a quick explanation.

Let's imagine an attacker has managed to change the contents of your Rooster file without you noticing. The contents were changed in such a way that your password to TorrentList.com is now actually your password to Google.com. You would be giving away your Google password to TorrentList.com.

Without a corruption check, this is theoretically possible. I'd recommend reading ["Using Encryption and Authentication Correctly"](https://paragonie.com/blog/2015/05/using-encryption-and-authentication-correctly) for more details.

The **corruption check works by checking a hash** generated each and everytime you use Rooster. This **hash is computed from (A) your passwords** in an encrypted form and **(B) your master password**. If you had a different master password, the hash would be different.

This is why if you type the wrong master password when using Rooster, the hash will be different even if the file is not corrupted.

**Comment by maxjacobson** [comment]
Thanks for explaining that!

I'm looking into making this change and ... I'll let you know if I can figure it out... but I may be at the limits of my rust knowledge 😅

**Comment by conradkleinespel** [comment]
@maxjacobson Alright ! Thanks for taking the time to look into it ! Please let me know (here or via email) if I can be of any help. I could give you some pointers, tell you what parts of the code might need changing, etc, if you think that can help you :wink:

**Comment by conradkleinespel** [comment]
@maxjacobson I'm having a go at this right now. Will push a first version of it on `master` tonight (without publishing to crates.io yet). I'll let you know so I can have your feedback (if you have the time to check it out).

**Comment by conradkleinespel** [comment]
@maxjacobson Alright, I've just pushed a new version of Rooster to `master`. Feel free to try it out and let me know what you think. If you find that it is not the right approach, we can re-evaluate the solution and re-open this issue :smiley:

**Comment by maxjacobson** [comment]
@conradkleinespel Hey, thanks for taking this on! I definitely like the output I'm seeing when I mistype my password. I'm not sure how, easily, to QA the path where I would see a different message, but it seems like a nice improvement to me 👍

**Comment by conradkleinespel** [comment]
@maxjacobson Awesome that you like the case where you mistype your password. That's a good start ! Thanks for your help by the way. I would have never worked on this if you hadn't taken the time to report your issue in the first place :smiley: 

Regarding QA, I'll be honest, I haven't properly tested all the cases myself. Before I release the next version stable version of Rooster, I plan on creating automated tests for these kinds of things though. So things will be a bit easier to reason about.

**Comment by maxjacobson** [comment]
Heh, my pleasure, and sounds good!
