### ISSUE TITLE
Multiple entries for same application

### ISSUE THREAD

**Issue by porto99** [conradkleinespel/rooster#52]
It would be nice if an application name could be used multiple times.
A common situation is an administrator using different logins on the same server, like
```
server_hot       root    pwd0
server_hot       smith   pwd1
server_yellow    root    pwd2
server_yellow    smith   pwd3
```
Presently rooster does not support it.

**Comment by porto99** [comment]
Didn't see #40, sorry for the noise.

**Comment by conradkleinespel** [comment]
Hi @porto99 ! Thanks for asking about this. Does #40 work for you too? If you'd rather have the ability to add the same multiple times, we could work on that :+1:
