### ISSUE TITLE
Analytics and tracking

### ISSUE THREAD

**Issue by conradkleinespel** [conradkleinespel/rooster#7]
**At some point, Rooster will include an "Analytics" module so that we can use data to make Rooster better. Let's see what this whole "Analytics" thing is about.**

Given the nature of Rooster, including some kind of tracking system inside of it could seem crazy. I get that. Matter of fact, when I am not sure what data is collected about me and/or don't understand what's being done with that data, I usually try to opt-out.

And, just so you know, **when Rooster gets analytics, there will be a way to opt-out**.

However, as with a lot of software projects, knowing what users do with the software helps in making it better. Here are some thing that I think Rooster could benefit from knowing:
- The Rooster commands you use (`rooster list`, `rooster get`, etc): this information could be used to removed unused commands or improve heavily used ones,
- Your locale: this could be used to translate Rooster documentation for heavily used languages,
- Your operating system: this could be used to focus testing efforts on those systems for every new release, so as to not lose users,
- Your version of Rooster: this could be used to drop support for older, unused versions, and focus development resources on what matters most.

These things will help make Rooster better for every user, including you. So yeah, at some point, Rooster will track how you use it. If you don't want to be tracked, you will be able opt-out.

Any feedback is welcome.

**Comment by sumproxy** [comment]
If tracking is involved, I'm afraid can't be involved with the project, sorry.

**Comment by conradkleinespel** [comment]
@sumproxy I'm sorry to hear that. I really appreciate that you spent time contributing to issues. So even though you don't want to get involved, thank you!

**Comment by sumproxy** [comment]
@conradkleinespel no problem

**Comment by qmx** [comment]
yeah, I'm out with tracking too, sorry :(

even if this is opt-out, Rooster is security-related software - contentions to even dreaming of phoning data back home.

**Comment by conradkleinespel** [comment]
Alright. Your call. Really, given that Rooster is open source, you could see what kind of data is sent "home" right in the source. There would be no funny business. But I get your point.

Thanks @qmx for participating !

**Comment by conradkleinespel** [comment]
@qmx & @sumproxy: Why do you refuse the idea of opt-out analytics? I'm interested in hearing your thoughts, if you have the time.

**Comment by sumproxy** [comment]
Because with time projects tend to get complicated and their code harder to analyze, so eventually for a person not actively involved with the project it will be hard to guarantee that "analytics and tracking" are not used against him, even when he has explicitly "opted out"

**Comment by sumproxy** [comment]
Anyway as @qmx said, for this kind of application this is not an option. This is the way it is for me

**Comment by conradkleinespel** [comment]
@sumproxy Alright, fair point about projects getting more complex and more difficult to analyze. Would it help if you could compile Rooster without analytics? Cargo has this thing called `features` that allows for conditional compilation. We could have a build without analytics for users that do not want them.

**Comment by sumproxy** [comment]
I’d rather not.

**Comment by conradkleinespel** [comment]
@sumproxy Alright. Thanks for all your feedback.

**Comment by conradkleinespel** [comment]
@sumproxy There will be no tracking in Rooster. See my comment on #2
