### ISSUE TITLE
build errors 

### ISSUE THREAD

**Issue by jigijigol** [conradkleinespel/rooster#72]
By building the program without lacking in any dependencies on MX-Linux Fluxbox 21 get these errors on terminal
 
# cargo install --root /usr rooster

    Updating crates.io index
  Installing rooster v2.9.0
   Compiling libc v0.2.132
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.43
   Compiling unicode-ident v1.0.3
   Compiling quote v1.0.21
   Compiling serde v1.0.144
   Compiling cc v1.0.73
   Compiling log v0.4.17
   Compiling pkg-config v0.3.25
   Compiling syn v1.0.99
   Compiling memchr v2.5.0
   Compiling getrandom v0.1.16
   Compiling regex-automata v0.1.10
   Compiling openssl v0.10.41
   Compiling bitflags v1.3.2
   Compiling ryu v1.0.11
   Compiling os_str_bytes v6.3.0
   Compiling hashbrown v0.12.3
   Compiling lazy_static v1.4.0
   Compiling foreign-types-shared v0.1.1
   Compiling serde_json v1.0.85
   Compiling serde_derive v1.0.144
   Compiling ppv-lite86 v0.2.16
   Compiling itoa v0.4.8
   Compiling textwrap v0.15.0
   Compiling once_cell v1.14.0
   Compiling remove_dir_all v0.5.3
   Compiling fastrand v1.8.0
   Compiling rooster v2.9.0
   Compiling strsim v0.10.0
   Compiling termcolor v1.1.3
   Compiling itoa v1.0.3
   Compiling ansi_term v0.12.1
   Compiling byteorder v1.4.3
   Compiling rprompt v1.0.5
   Compiling indexmap v1.9.1
   Compiling openssl-sys v0.9.75
   Compiling clap_lex v0.2.4
   Compiling foreign-types v0.3.2
   Compiling dirs-sys v0.3.7
   Compiling atty v0.2.14
   Compiling tempfile v3.3.0
   Compiling rpassword v5.0.1
   Compiling xcb v0.8.2
   Compiling csv-core v0.1.10
   Compiling bstr v0.2.17
   Compiling rand_core v0.5.1
   Compiling dirs v3.0.2
   Compiling clap v3.2.20
   Compiling csv v1.1.6
   Compiling rand_chacha v0.2.2
   Compiling openssl-macros v0.1.0
   Compiling rand v0.7.3
   Compiling x11-clipboard v0.3.3
   Compiling clipboard v0.5.0
error[E0599]: no variant or associated item named `HelpRequired` found for enum `AppSettings` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:300:38
    |
300 |         .global_setting(AppSettings::HelpRequired)
    |                                      ^^^^^^^^^^^^ variant or associated item not found in `AppSettings`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:310:22
    |
310 |                     .about("Forces initializing the file, used in integration tests only"),
    |                      ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:319:26
    |
319 |                         .about("The name of the app (fuzzy-matched)"),
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:324:26
    |
324 |                         .about("Your username for this account"),
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:330:26
    |
330 |                         .about("Show the password instead of copying it to the clipboard"),
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:339:26
    |
339 |                         .about("The name of the app (fuzzy-matched)"),
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:345:26
    |
345 |                         .about("Show the password instead of copying it to the clipboard"),
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:352:22
    |
352 |                     .about("The name of the app (fuzzy-matched)"),
    |                      ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:361:26
    |
361 |                         .about("The name of the app (fuzzy-matched)"),
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:366:26
    |
366 |                         .about("Your username for this account"),
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:372:26
    |
372 |                         .about("Show the password instead of copying it to the clipboard"),
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:378:26
    |
378 |                         .about("Only use alpha numeric (a-z, A-Z, 0-9) in generated passwords"),
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:385:26
    |
385 |                         .about("Set a custom length for the generated password")
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:395:26
    |
395 |                         .about("The name of the app (fuzzy-matched)"),
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:401:26
    |
401 |                         .about("Show the password instead of copying it to the clipboard"),
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:407:26
    |
407 |                         .about("Only use alpha numeric (a-z, A-Z, 0-9) in generated passwords"),
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:414:26
    |
414 |                         .about("Set a custom length for the generated password")
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:424:26
    |
424 |                         .about("The name of the app (fuzzy-matched)"),
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:430:26
    |
430 |                         .about("Show the password instead of copying it to the clipboard"),
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:439:26
    |
439 |                         .about("The current name of the app (fuzzy-matched)"),
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:444:26
    |
444 |                         .about("The new name of the app"),
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:453:26
    |
453 |                         .about("The current name of the app (fuzzy-matched)"),
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:458:26
    |
458 |                         .about("Your new username for this account"),
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:472:34
    |
472 | ...                   .about("The path to the file you want to import"),
    |                        ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:481:34
    |
481 | ...                   .about("The path to the file you want to import"),
    |                        ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:490:34
    |
490 | ...                   .about("The path to the file you want to import"),
    |                        ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:512:26
    |
512 |                         .about("The log2n parameter")
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:518:26
    |
518 |                         .about("The r parameter")
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:524:26
    |
524 |                         .about("The p parameter")
    |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rooster-2.9.0/src/lib.rs:531:26
    |
531 |                         .about("Disable parameter checks"),
    |                          ^^^^^ method not found in `Arg<'_>`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `rooster` due to 30 previous errors
error: failed to compile `rooster v2.9.0`, intermediate artifacts can be found at `/tmp/cargo-installFynSyz`

**Comment by conradkleinespel** [comment]
:wave: Hello there. It builds fine for me with Rust 1.62.1 on Linux. Have you tried building `clap` (https://github.com/clap-rs/clap) on its own without Rooster? Does that work?

**Comment by jigijigol** [comment]
Thank you very much for your simple and good password manager. Hope you always be successful and best wishes. :-)

**Comment by conradkleinespel** [comment]
Thanks ! And great that is it working for you now. I'll make a note to publish again to crates.io at some point. Maybe I need to publish with updates so that it compiles correctly on all systems :shrug:
