### ISSUE TITLE
Unable to use/install rooster with latest version of libsodium

### ISSUE THREAD

**Issue by ZaClF** [conradkleinespel/rooster#79]
I am using MAC M2. I can use rooster before. Today I updated my software and now I can neither use or install rooster.

When I run 'rooster' command, the error message goes like this `dyld[41309]: Library not loaded: /opt/homebrew/opt/libsodium/lib/libsodium.23.dylib`

And when I reinstall rooster, the error message goes like this 

```
ld: library sodium not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I can see that the rooster trying to access `libsodium.23.dylib`. However, the latest version of libsodium has `libsodium.26.dylib`

Could you please fix this?

**Comment by conradkleinespel** [comment]
Hi @ZaClF,

Not sure what the root cause is, I don't have a Mac, unfortunately. But let's see if we can find a way to make it work.

When you say that you tried to reinstall rooster, what were the commands you ran to reinstall it?

Can you provide the output of the following commands?

```shell
brew info libsodium
cargo install -vv --all-features --root /usr rooster
```

I also asked ChatGPT and it suggests the following, which may or may not make sense:

```shell
ln -s /opt/homebrew/opt/libsodium/lib/libsodium.26.dylib /opt/homebrew/opt/libsodium/lib/libsodium.23.dylib
```

Cheers !

**Comment by ZaClF** [comment]
This command actually solved my problem. Thank you!
But I think this is a temporary solution. 

for `brew info libsodium`, I got
```
==> libsodium: stable 1.0.19 (bottled), HEAD
NaCl networking and cryptography library
https://libsodium.org/
/opt/homebrew/Cellar/libsodium/1.0.19 (78 files, 1MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-11-21 at 21:31:02
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/lib/libsodium.rb
License: ISC
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 65,608 (30 days), 110,111 (90 days), 265,619 (365 days)
install-on-request: 4,447 (30 days), 6,153 (90 days), 9,666 (365 days)
build-error: 5 (30 days)
```

For rooster `command`, I got

```
dyld[55405]: Library not loaded: /opt/homebrew/opt/libsodium/lib/libsodium.23.dylib
  Referenced from: <7B7DB68C-51B6-3C4A-84CF-8A7B375CC722> /Users/zhujiang/.cargo/bin/rooster
  Reason: tried: '/Users/zhujiang/.wasmedge/lib/libsodium.23.dylib' (no such file), '/opt/homebrew/opt/libsodium/lib/libsodium.23.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libsodium/lib/libsodium.23.dylib' (no such file), '/opt/homebrew/opt/libsodium/lib/libsodium.23.dylib' (no such file), '/usr/local/lib/libsodium.23.dylib' (no such file), '/usr/lib/libsodium.23.dylib' (no such file, not in dyld cache), '/Users/zhujiang/.wasmedge/lib/libsodium.23.dylib' (no such file), '/opt/homebrew/Cellar/libsodium/1.0.19/lib/libsodium.23.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/libsodium/1.0.19/lib/libsodium.23.dylib' (no such file), '/opt/homebrew/Cellar/libsodium/1.0.19/lib/libsodium.23.dylib' (no such file), '/usr/local/lib/libsodium.23.dylib' (no such file), '/usr/lib/libsodium.23.dylib' (no such file, not in dyld cache)
[1]    55405 abort      rooster
```

**Comment by conradkleinespel** [comment]
Ok, good first step!

When you say that you tried to reinstall rooster, what were the commands you ran to reinstall it?

You could try doing a `git clone `, then edit `Cargo.toml` and for the [last 2 lines](
https://github.com/conradkleinespel/rooster/blob/master/Cargo.toml#L31-L32), use this:
```toml
rclio = { path = "../rclio", version = "0.0" }
rtoolbox = { path = "../rtoolbox", features = ["serde"], version = "0.0" }
```

Then run `cargo run`. Does that work? If yes, run `cargo install --all-features --root /usr`.

**Comment by ZaClF** [comment]
For debugging purpose, I reverted this command 
`ln -s /opt/homebrew/opt/libsodium/lib/libsodium.26.dylib /opt/homebrew/opt/libsodium/lib/libsodium.23.dylib`
and tried to install rooster from source code.

I cloned the repo and modified the` Cargo.toml`. But` cargo run` still goes
```
= note: ld: warning: ignoring duplicate libraries: '-lSystem'
          ld: library 'sodium' not found
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

BTW, the installation command for MAC `cargo install --all-features --root /usr` is actually not working even for the times when I can successfully install rooster. This is because MAC OS have very strict permission management. You **can not** install program directly under /usr even if you use `sudo`. Therefore, I simply use `cargo install --all-features`  to install rooster.
This way the rooster is installed under personal home directory.

So, maybe considering updating `README.md`? 
Really sorry, should have mentioned this earlier. Really appreciate your effort contributing to the community.

**Comment by conradkleinespel** [comment]
That's really odd, I'm not sure how to further test this. Have you tried reinstalling libsodium?

At this point, I wonder if maybe I should remove the libsodium dependency altogether. I've drafted this pull request which removes libsodium in favor of pure-rust alternatives. https://github.com/conradkleinespel/duck/pull/64

**Comment by conradkleinespel** [comment]
Something else you could try if you haven't already is updating your version of rust/cargo.

**Comment by ZaClF** [comment]
> Have you tried reinstalling libsodium?

Yes, I have. Sadly didn't work

> Something else you could try if you haven't already is updating your version of rust/cargo.

Also didn't work..

Anyway, I am currently ok with the temporary solution. So, good luck!

Nice repo BTW. Been using rooster for two years

**Comment by conradkleinespel** [comment]
> Yes, I have. Sadly didn't work

Ah, too bad.

Ok, here's one last try: I've now removed the dependency on libsodium, I've also removed the dependency on openssl. Would you mind re-trying the `git clone ...` steps as explained here: https://github.com/conradkleinespel/rooster/issues/79#issuecomment-1823278525

That should work now, since there is no dynamic linking at all left in the code. Let me know if that works :+1: 
I've tested locally and it works for me, but I'd love your feedback before publishing a new release.

**Comment by conradkleinespel** [comment]
> Nice repo BTW. Been using rooster for two years

Wow, nice! I'm glad it's been useful! :smiley:

**Comment by conradkleinespel** [comment]
> Nice repo BTW. Been using rooster for two years

Wow, nice! I'm glad it's been useful! :smiley: 

> Yes, I have. Sadly didn't work

Ah, too bad.

Ok, here's one last try. I've now removed the dependency on libsodium, I've also removed the dependency on openssl.

⚠️  _First, backup your rooster file somewhere safe._

Then, would you mind re-trying the `git clone ...` steps as explained here: https://github.com/conradkleinespel/rooster/issues/79#issuecomment-1823278525

That should work now, since there is no dynamic linking at all left in the code. Let me know if that works :+1: 
I've tested locally and it works for me, but I'd love your feedback before publishing a new release.

**Comment by ZaClF** [comment]
IT WORKS FINE!!
Really appreciate your effort!! Thank you very much!

**Comment by conradkleinespel** [comment]
Glad to hear that! And thanks for your help as well
